# Generated by Django 5.1.5 on 2025-06-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_color_producto_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='talla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
