# Generated by Django 5.1.5 on 2025-06-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_color_talla_remove_producto_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='colores',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tallas',
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
