# Generated by Django 5.1.5 on 2025-06-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_producto_colores_remove_producto_tallas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(to='productos.color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(to='productos.talla'),
        ),
    ]
