# Generated by Django 5.1.5 on 2025-06-19 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_remove_producto_color_remove_producto_talla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.color'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.talla'),
        ),
    ]
