# Generated by Django 5.1.5 on 2025-06-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_mensajecontacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensajeContacto',
        ),
    ]
