# Generated by Django 5.1.5 on 2025-06-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_producto_creador_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
