# Generated by Django 5.1.5 on 2025-06-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_alter_itemcarrito_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
