# Generated by Django 5.1.5 on 2025-06-25 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_pedido_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
